language: node_js
node_js:
- 6.10.3
branches:
  only:
  - hexo

install:
- npm install -g hexo-cli
- npm install

before_script:
- git config --global user.name "iChenwin"
- git config --global user.email "iChenwin@gmail.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script: hexo clean && hexo generate && hexo deploy